[tool.black]
line_length = 88
target_version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | __pycache__
  | venv
)/
'''

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
allow_redefinition = false
warn_unused_configs = true

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88

[tool.ruff]
ignore = ["E501"]
